spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: user
    password: password
  mvc:
    path match:
      matching-strategy: ant_path_matcher
# FIXME: just example. Normally credentials should no be here.
defaultCredentials:
  admin:
    login: admin
    password: Admin!123
  user:
    login: user
    password: Password!123