spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: db/migration
    enabled: true
    table: schema_history_table
    baseline-on-migrate: true
    out-of-order: true
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: true
      mode: always
  mvc:
    format:
      date: iso
      date-time: iso
    path match:
      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api
# FIXME: just example
defaultCredentials:
  admin:
    login: ${ADMIN_LOGIN_BOOKS_CATALOG}
    password: ${ADMIN_PASSWORD_BOOKS_CATALOG}
  user:
    login: ${USER_LOGIN_BOOKS_CATALOG}
    password: ${USER_PASSWORD_BOOKS_CATALOG}